version: '3.2'

services:
  db:
    build: .
    image: mcmoe/mssqldocker:v2017.CU20.0
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: GZVjGgOs3Z6D
      MSSQL_DB: TEST_SPRINGBOOT_REST_WS
      MSSQL_USER: ADMCONTRACTZIT
      MSSQL_PASSWORD: eNbqetRjVQBc
    ports:
      - "1433:1433"
    container_name: mssqldev
